databases:
  - name: movie-theater-db
    plan: free
    databaseName: movie_theater_booking
    user: movie_user

services:
  - type: web
    plan: free
    name: movie-theater-booking
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn movie_theater_booking.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movie-theater-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4